remove shlib.sh import

diff --git a/git/bin/git-fetch b/git/bin/git-fetch
--- a/git/bin/git-fetch
+++ b/git/bin/git-fetch
@@ -1,11 +1,15 @@
 #!/bin/bash
 
-git_fetch() {
-    shlib="$(readlink -f ~/bin/shlib.sh)"
-    test -f "$shlib" || return
-    # shellcheck source=/dev/null
-    . "$shlib"
+require_command() {
+    for c in "$@"; do
+        command -v "$c" >/dev/null || {
+            echo >&2 "required command '$c' is not installed, aborting..."
+            exit 1
+        }
+    done
+}
 
+git_fetch() {
     require_command git parallel
 
     repo_dir="$(dirname "$(realpath -s "$1")")"
diff --git a/git/bin/git-rename b/git/bin/git-rename
--- a/git/bin/git-rename
+++ b/git/bin/git-rename
@@ -5,6 +5,15 @@
 # ref: https://help.github.com/en/github/using-git/changing-author-info
 # ref: https://developer.github.com/v3/users/
 
+require_command() {
+    for c in "$@"; do
+        command -v "$c" >/dev/null || {
+            echo >&2 "required command '$c' is not installed, aborting..."
+            exit 1
+        }
+    done
+}
+
 usage() {
     this="$(readlink -f "$0")"
 
@@ -57,11 +66,6 @@ git_rename() {
 }
 
 main() {
-    shlib="$(readlink -f ~/bin/shlib.sh)"
-    test -f "$shlib" || return
-    # shellcheck source=/dev/null
-    . "$shlib"
-
     export OLD_GIT_COMMITTER_EMAIL="${OLD_GIT_COMMITTER_EMAIL}"
     test -n "$OLD_GIT_COMMITTER_EMAIL" || usage
 
