git: update git-secrets hooks script

diff --git a/git/.config/git/templates/hooks/prepare-commit-msg b/git/.config/git/templates/hooks/prepare-commit-msg
--- a/git/.config/git/templates/hooks/prepare-commit-msg
+++ b/git/.config/git/templates/hooks/prepare-commit-msg
@@ -1,3 +1,7 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
+command -v git-secrets >/dev/null 2>&1 || {
+    echo >&2 "\nThis repository is configured for git-secrets but 'git-secrets' was not found on your path. You can install it on 'https://github.com/awslabs/git-secrets'.\n"
+    exit 2
+}
 git secrets --prepare_commit_msg_hook -- "$@"
