scripts: add function check_exec for bash scripts

diff --git a/scripts/bin/git-clone b/scripts/bin/git-clone
--- a/scripts/bin/git-clone
+++ b/scripts/bin/git-clone
@@ -1,9 +1,14 @@
 #! /bin/bash
 
-hash git 2>/dev/null || {
-    echo >&2 "Required command 'git' is not installed. Aborting."
-    exit 1
+function check_exec() {
+    for exe in $@; do
+        hash "$exe" 2>/dev/null || {
+            echo >&2 "Required command '$exe' is not installed. Aborting."
+            exit 1
+        }
+    done
 }
+check_exec git
 
 repo="$1"
 code_dir="$HOME/code"
diff --git a/scripts/bin/git-remote b/scripts/bin/git-remote
--- a/scripts/bin/git-remote
+++ b/scripts/bin/git-remote
@@ -1,14 +1,14 @@
 #! /bin/bash
 
-hash parallel 2>/dev/null || {
-    echo >&2 "Required command 'parallel' is not installed. Aborting."
-    exit 1
+function check_exec() {
+    for exe in $@; do
+        hash "$exe" 2>/dev/null || {
+            echo >&2 "Required command '$exe' is not installed. Aborting."
+            exit 1
+        }
+    done
 }
-
-hash git 2>/dev/null || {
-    echo >&2 "Required command 'git' is not installed. Aborting."
-    exit 1
-}
+check_exec parallel git
 
 function git_remote() {
     local repo="${1%.git}"
diff --git a/scripts/bin/git-rename b/scripts/bin/git-rename
--- a/scripts/bin/git-rename
+++ b/scripts/bin/git-rename
@@ -5,10 +5,15 @@
 # ref: https://help.github.com/en/github/using-git/changing-author-info
 # ref: https://developer.github.com/v3/users/
 
-hash git 2>/dev/null || {
-    echo >&2 "Required command 'git' is not installed. Aborting."
-    exit 1
+function check_exec() {
+    for exe in $@; do
+        hash "$exe" 2>/dev/null || {
+            echo >&2 "Required command '$exe' is not installed. Aborting."
+            exit 1
+        }
+    done
 }
+check_exec git
 
 function usage() {
     cat <<EOF
