bin: add script ~/bin/git-{fetch,remote}

diff --git a/bin/bin/git-clone b/bin/bin/git-clone
--- a/bin/bin/git-clone
+++ b/bin/bin/git-clone
@@ -1,5 +1,10 @@
 #! /bin/bash
 
+hash git 2>/dev/null || {
+    echo >&2 "Required command 'git' is not installed. Aborting."
+    exit 1
+}
+
 repo="$1"
 code_dir="$HOME/code"
 
